title: "Blog de prueba"
date: 2021/11/22
author: alecereijo
email: your-email@domain.com
description: > Este blog es una prueba del tutorial de github

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
